### ISSUE TITLE
能提供下数据库sql文件吗

### ISSUE THREAD

**Issue by zhou997** [BooksCup/wechat#1]
能提供下数据库sql文件吗？

**Comment by BooksCup** [comment]
好的，明天我push上去，还没开发完成所以没提交




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhouweixuan"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 晚上6:10
收件人:&nbsp;"BooksCup/wechat"<wechat@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[BooksCup/wechat] 能提供下数据库sql文件吗 (#1)




能提供下数据库sql文件吗？

**Comment by BooksCup** [comment]
push了，地址:https://github.com/BooksCup/wechat-server/blob/master/sql/wechat_server.sql

**Comment by zhou997** [comment]
> push了，地址:https://github.com/BooksCup/wechat-server/blob/master/sql/wechat_server.sql

多谢
